### ISSUE TITLE
请指导一下

### ISSUE THREAD

**Issue by MarcoChong** [cuiods/HostelWorld#1]
新人一个，想知道怎么运行这个项目？

**Comment by cuiods** [comment]
@MarcoChong 
 1. 新建Mysql数据库hostel，导入项目根目录的hostel.sql文件
 2. 编译项目，运行HostelWorldApplication中的main方法
 3. 访问[http://localhost:8080/swagger-ui.html](http://localhost:8080/swagger-ui.html)查看后端API
 4. 前端项目运行需要查看[系统前端](https://github.com/cuiods/HostelWorld-Front)
 5. 如果需要部署，使用mvn package -Dmaven.test.skip=true打包，然后直接运行java -jar [name].jar即可。
